services:
  - type: web
    name: omninote-core
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

  - type: web
    name: omninote-vault-web
    env: static
    rootDir: web_app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
