services:
  - type: web
    name: omninote-core
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
